### ISSUE TITLE
how to set NFTPort Gallary?

### ISSUE THREAD

**Issue by khw0114** [Worldsz/NFT-Unity3D-Metaverse-Template#1]
I want to make the NFTPort gallery Unity through your asset.
What should I do?

**Comment by saszer** [comment]
Hi there, it is very easy: 
1. Clone and Open in Unity

2. You just need to set up your APIKey in NFTPort/Home in the top window bar of the project.
https://docs.nftport.xyz/docs/nftport/ZG9jOjUwMzc2NzA5-getting-started#getting-started

3. Then in the scene, just copy the Gallery Object to your scene if you need to, 
 - Under this Object, there are frame prefabs, Arrange these frames in however shape/size to meet your metaverse/game needs.
 
 Let us know,

**Comment by Hye1Kim** [comment]
Thank you for your answer.
I want to make a gallery using your NFT-Unity3D-Metaverse-Template. However, I have a few questions.
How do I upload files from gallery template, get nft issued, and register my nft in gallery?

**Comment by saszer** [comment]
Hi @Hye1Kim , Gallery is a read NFT data example. It will read all the NFTs in the collection or an account. To register/issue your NFT you need to use any of the write/Mint endpoints. 

Easiest to start is with [easy mint URL: ](https://docs.nftport.xyz/docs/nftport/ZG9jOjU1MDM4OTgw-easy-minting-w-url) or [East Mint FIle](https://docs.nftport.xyz/docs/nftport/ZG9jOjczMDEwMjIx-easy-minting-with-file-upload) components. 

If you would like to mint to your own collection and add more custom attribute and metadata to your NFT use [Custom Mint](https://docs.nftport.xyz/docs/nftport/ZG9jOjYzMDIzNDgx-customizable-minting) , it involves multiple steps and you will need to also use [storage features](https://docs.nftport.xyz/docs/nftport/ZG9jOjYwODM0NTY3-storage-upload-file) there.

Once you mint it to the wallet, you can query the gallery and NFT will show up, it may take a minute or two to register and if it doesn't [let us know. ](https://discord.gg/w92sXkNmBR).

There's a PR #2 open which will show examples of it once finalised.

**Comment by khw0114** [comment]
Hello, Thanks for the reply.
But my NFT doesn't appear in the gallery yet.
I'll show you my work below.

1. Easy Mint URL 

![Screenshot from 2022-09-15 15-52-25](https://user-images.githubusercontent.com/57400038/190544801-6c59bea1-55d0-47b6-aa58-55fa29837b17.png)

Mint was successful through Easy Mint URL, and Mint to Address used the rinkeby address of my Metamask.


Screenshot from 2022-09-15 15-52-25.png
fig 1 . Sucess Easy Mint URL 

abf0976b-9814-49d3-8e3b-2b8a1d38151c.png
  fig 2 . Sucess Easy Mint URL   -  Metadata
image.png
fig 3. my Account - Rinkeby Test Network

Screenshot from 2022-09-15 15-57-15.png 
fig 4-1.  A list of NFTs I have minted 
Screenshot from 2022-09-15 15-57-17.png
fig 4-2.  A list of NFTs I have minted (scroll ->)




2. Connet Address ( [NFT-Unity3D-Metaverse-Template](https://github.com/nftport/NFT-Unity3D-Metaverse-Template))

I can't see anything even though I did mint.


Screenshot from 2022-09-15 15-57-51.png
fig 5. Enter my address > Connect address

Screenshot from 2022-09-16 11-04-31.png
fig 6. I can't see anything

Screenshot from 2022-09-16 11-05-09.png
fig 7-1. Iogs
Screenshot from 2022-09-16 11-05-19.png
fig 7-2. Iogs
Screenshot from 2022-09-16 11-05-13.png
fig 7-3. Iogs
Screenshot from 2022-09-16 11-05-15.png
fig 7-4. Iogs

I really want to make a nice nftport using your nftport. Help me

**Comment by khw0114** [comment]
Hello, Thanks for the reply.
But my NFT doesn't appear in the gallery yet.
I'll show you my work below.

**1. Easy Mint URL** 

Mint was successful through Easy Mint URL, and Mint to Address used the rinkeby address of my Metamask.

![Screenshot from 2022-09-15 15-52-25](https://user-images.githubusercontent.com/57400038/190545045-7fae7d6f-f7f7-4a61-8318-d1d91699a01b.png)
fig 1 . Sucess Easy Mint URL 

![Screenshot from 2022-09-15 15-52-46](https://user-images.githubusercontent.com/57400038/190545075-690fa64f-e35d-404c-af98-8030ca106d31.png)
  fig 2 . Sucess Easy Mint URL   -  Metadata

![image](https://user-images.githubusercontent.com/57400038/190553217-8edce1e9-063d-4be9-9d60-dc5f27444964.png)
fig 3. my Account - Rinkeby Test Network

![Screenshot from 2022-09-15 15-57-15](https://user-images.githubusercontent.com/57400038/190545164-b4a14a1a-4d91-4f2e-a15e-5fc106ecbfc2.png)
fig 4-1.  A list of NFTs I have minted 

![Screenshot from 2022-09-15 15-57-17](https://user-images.githubusercontent.com/57400038/190545222-6af4f9e2-cf07-4b86-b666-3475e6a0e71a.png)
fig 4-2.  A list of NFTs I have minted (scroll ->)




**2. Connet Address ( [NFT-Unity3D-Metaverse-Template](https://github.com/nftport/NFT-Unity3D-Metaverse-Template))**

I can't see anything even though I did mint.

![Screenshot from 2022-09-15 15-57-51](https://user-images.githubusercontent.com/57400038/190545571-ea94113b-86f9-4267-8c22-375f351313a3.png)
fig 5. Enter my address > Connect address

![Screenshot from 2022-09-16 11-04-31](https://user-images.githubusercontent.com/57400038/190545349-845891f0-ce2b-42ad-83be-203908647f39.png)
fig 6. I can't see anything

![Screenshot from 2022-09-16 11-05-09](https://user-images.githubusercontent.com/57400038/190545392-b8e1a03e-b54b-4ec8-912f-f75998540d31.png)
fig 7-1. Iogs

![Screenshot from 2022-09-16 11-05-13](https://user-images.githubusercontent.com/57400038/190545413-7df8de0b-7d10-4d3b-9d77-c475e04407c9.png)
fig 7-2. Iogs

![Screenshot from 2022-09-16 11-05-15](https://user-images.githubusercontent.com/57400038/190545432-aaea4e31-a15a-4e0b-9f00-ad57e86ef089.png)
fig 7-3. Iogs

![Screenshot from 2022-09-16 11-05-19](https://user-images.githubusercontent.com/57400038/190545448-05d2ca02-ebbc-4bb1-94cf-11a81580b1ec.png)
fig 7-4. Iogs

I really want to make a nice nft gallary using your nftport. Help me

**Comment by saszer** [comment]
@khw0114  Thanks for posting the elaborated steps. super appreciate it. The issue has been solved now and all minted NFTs are visible in NFTs of account feature. 

I would also recommend disabling the big gallery and using the smaller gallery in the hierarchy or reduce the number of frame prefabs to your liking for small collections/accounts.

Let us know if you're still facing any difficulties. 

PS, if you would like to use custom mint, you need to deploy your own erc721 contract here with same API key and input that in the contract field of custom mint. 
https://docs.nftport.xyz/docs/nftport/b3A6Njg1NTI0MTI-deploy-a-contract-for-nft-products

Best, looking forward to what you build.

**Comment by Hye1Kim** [comment]
Hello
Thanks to you, I solved the problem well.
