### ISSUE TITLE
How do I register NFT with multiple accounts in one collection?

### ISSUE THREAD

**Issue by Hye1Kim** [Worldsz/NFT-Unity3D-Metaverse-Template#3]
Hello,
I want to register NFT with multiple accounts in one collection so that I can see NFT works registered with multiple accounts in the gallery at a glance.
Currently, we have distributed the collection, but it has not been progressed since then. How shall I do it?

**Comment by saszer** [comment]
Can you please elaborate on what you mean by registering NFT with multiple accounts? 

1. do you mean mint same NFT token ID to multiple accounts? That is possible if NFT is of type erc1155, currently, only erc721 is supported where each NFT token ID is unique, erc1155 support will be there in next months.
2. or do you mean reading the NFT data from multiple accounts? In that case you'll need to mod https://github.com/nftport/sample-unity3D-nft-metaverse-template/blob/main/Assets/Advanced%20Playground/Gallery/Gallery.cs#L146 when OnComplete, where NFTsofUser is returned, you can add another users NFTs to the same NFTs_model.

**Comment by Hye1Kim** [comment]
I'd like to display NFTs created with different accounts in one gallery.
For example, if you have NFT1 created with account A, NFT2 created with account B, and NFT3 created with account C, I want to see NFT1, NFT2, and NFT3 together in one gallery.
However, the only way to access the gallery is "connect address/metamask" or "view collection" (fig1.), so I wonder what I should do if I want to organize the gallery as described above.
![image](https://user-images.githubusercontent.com/102787163/191906111-e6c8722a-66cd-48f6-90ea-feef2a6c5274.png)
fig 1. way to access the gallery

**Comment by saszer** [comment]
1. If its different account and different collections, will need to add in mod this quite a bit and some extra code here 
https://github.com/nftport/sample-unity3D-nft-metaverse-template/blob/main/Assets/Advanced%20Playground/Gallery/Gallery.cs#L146 and have an input UI which can take multiple accounts via [gallery Controller](https://github.com/nftport/sample-unity3D-nft-metaverse-template/blob/main/Assets/Advanced%20Playground/Gallery/GalleryController.cs). 

2. But I would recommend instead, have the users mint NFTs to your collection via [custom mint feature](https://docs.nftport.xyz/docs/nftport/ZG9jOjYzMDIzNDgx-customizable-minting). You can just query collection NFTs as it is in the gallery and it will show all NFTs in that collection from all different accounts.

My question here would be, wich NFTs of multiple users would you like to show?  How are those minted?
1. NFT tied to your product - then use custom mint so users can mint your collection.
2. or, Any/All NFTs of multiple users all at once.

**Comment by Hye1Kim** [comment]
Hello,
As far as I understand your explanation, if I create my collection and custom mint it with a different account, I can see all the nfts through my collection, right?
However, when I try, the following errors continue to occur. I captured my work and attached it below. I'd appreciate it if you could check it.

1.  Deploy an NFT collection contract using collection api 
![image](https://user-images.githubusercontent.com/102787163/192206683-9c70d6bc-8ff7-4677-9868-1e96ae55960d.png)
fig 1-1. Deploy an NFT collection contract (1)
![image](https://user-images.githubusercontent.com/102787163/192206877-6c9088f8-063b-4a22-974f-6f94a9f86b08.png)
fig 1-2. Deploy an NFT collection contract (2)

2. Custom Mint
Contract Address : 0x2baf9a3e605b8abcc86cd03d4b0f45fea1d5529f (Deployed collection contract address)
Mint to Address : 0xDDa30eCbaCD4ccd1F9F6faD86753d2c0e3293909 (The account that deployed the collection contract)

![tempsnip](https://user-images.githubusercontent.com/102787163/192207796-7c32a984-a10a-451d-bb19-c36045e756c9.png)
fig 2. custom mint

![image](https://user-images.githubusercontent.com/102787163/192208531-83f555d6-91c9-4f45-a4c3-b22c0cf2caa0.png)
fig 3. custom mint log-1

![image](https://user-images.githubusercontent.com/102787163/192208587-1bb5c31d-a61e-42b7-a06b-4919ce8ff87c.png)
fig 4. custom mint log-2

![image](https://user-images.githubusercontent.com/102787163/192208681-8563b73d-00bd-43cb-ba80-8086e0a87cf1.png)
fig 5. custom mint log-3

![image](https://user-images.githubusercontent.com/102787163/192208745-d20790ba-e327-4bfc-8b1f-7408b2d1edfc.png)
fig 7. custom mint log-4

**Comment by saszer** [comment]
Hi @Hye1Kim , 
Just checked and the contract 0x2baf9a3e605b8abcc86cd03d4b0f45fea1d5529f  you have deployed is a collection contract and not a product contract as mentioned in steps in [Customizable minting](https://docs.nftport.xyz/docs/nftport/ZG9jOjYzMDIzNDgx-customizable-minting) , Please deploy a contract via this page 
https://docs.nftport.xyz/docs/nftport/b3A6Njg1NTI0MTI-deploy-a-contract-for-nft-products , and use that one. 

Also make sure the APIKey you are putting in SDK and the one you deploy the contract from is same.
